name: My First Github Actions Workflow

on:

  push:
  workflow_dispatch:

jobs:

  hello-world:
  
    runs-on: ubuntu-latest

    steps:

      - name: say hello 

        run: echo "hello bigboss! my Github Actions workflow is working!"